### ISSUE TITLE
Is this trained by multiple micro-hybrid expert models?

### ISSUE THREAD

**Issue by musellama** [yyyyyt123/dynamic-moe-deepspeed#5]
Is this trained by multiple micro-hybrid expert models?

**Comment by yyyyyt123** [comment]
It was trained by hybird (data-parallel and expert-parallel), we aimed to change the deployment of expert on the fly. However, this project is inactive. For more advanced MoE training system, I recommend referring to recent papers presented at the ATC 2023 conference.
